version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=concepts

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: '1234'
    ports:
      - '80:80'
    depends_on:
      - postgres
